SELECT
  LTRIM(RTRIM(SYSIBM.SYSTABLES.DBNAME)) AS TABLE_CATALOG,
  LTRIM(RTRIM(SYSIBM.SYSTABLES.CREATOR)) AS TABLE_SCHEMA,
  LTRIM(RTRIM(SYSIBM.SYSTABLES.NAME)) AS TABLE_NAME,
  SYSIBM.SYSTABLES.CREATEDTS,
  SYSIBM.SYSTABLES.ALTEREDTS,
  LTRIM(RTRIM(SYSIBM.SYSTABLESPACE.NAME)) AS TABLE_SPACE
FROM
  SYSIBM.SYSTABLES
  INNER JOIN SYSIBM.SYSTABLESPACE
    ON SYSIBM.SYSTABLES.TSNAME = SYSIBM.SYSTABLESPACE.NAME
WITH UR
