SELECT
  NULLIF(1, 1) AS TABLE_CATALOG,
  STRIP(COLUMNS.TABSCHEMA) AS TABLE_SCHEMA,
  STRIP(COLUMNS.TABNAME) AS TABLE_NAME,
  STRIP(COLUMNS.COLNAME) AS COLUMN_NAME
FROM
  SYSCAT.COLUMNS AS COLUMNS
WHERE
  COLUMNS.HIDDEN = 'I'
ORDER BY
  COLUMNS.TABSCHEMA,
  COLUMNS.TABNAME,
  COLUMNS.COLNAME
WITH UR 

-- Z/OS 
SELECT
  NULLIF(1, 1) AS TABLE_CATALOG,
  STRIP(SYSIBM.SYSCOLUMNS.TBCREATOR) AS TABLE_SCHEMA,
  STRIP(SYSIBM.SYSCOLUMNS.TBNAME) AS TABLE_NAME,
  STRIP(SYSIBM.SYSCOLUMNS.NAME) AS COLUMN_NAME
FROM
  SYSIBM.SYSCOLUMNS AS COLUMNS
WHERE
  SYSIBM.SYSCOLUMNS.HIDDEN = 'R' OR SYSIBM.SYSCOLUMNS.HIDDEN = 'P'
ORDER BY
  SYSIBM.SYSCOLUMNS.TBCREATOR,
  SYSIBM.SYSCOLUMNS.TBNAME,
  SYSIBM.SYSCOLUMNS.NAME
WITH UR 