SELECT
	NULLIF(1,1) AS PKTABLE_CAT,
	B.REFTBCREATOR AS PKTABLE_SCHEM,
	B.REFTBNAME AS PKTABLE_NAME,
	A.COLNAME AS PKCOLUMN_NAME,
	NULLIF(1,1) AS FKTABLE_CAT,
	A.CREATOR AS FKTABLE_SCHEM,
	A.TBNAME AS FKTABLE_NAME,
	A.COLNAME AS FKCOLUMN_NAME,
	A.COLSEQ AS KEY_SEQ,
	NULLIF(1,1) AS UPDATE_RULE,
	B.DELETERULE AS DELETE_RULE,
	A.RELNAME AS FK_NAME,
	B.IXNAME AS PK_NAME,
	NULLIF(1,1) AS DEFERRABILITY,
	NULLIF(1,1) AS UNIQUE_OR_PRIMARY
FROM
SYSIBM.SYSFOREIGNKEYS A,
SYSIBM.SYSRELS B
WHERE A.RELNAME = B.RELNAME
AND B.REFTBCREATOR = A.CREATOR
