SELECT
  NULLIF(1, 1)
    AS ROUTINE_CATALOG,
  STRIP(SYSIBM.SYSROUTINES.SCHEMA)
    AS ROUTINE_SCHEMA,
  STRIP(SYSIBM.SYSROUTINES.NAME)
    AS ROUTINE_NAME,
  STRIP(SYSIBM.SYSROUTINES.SPECIFICNAME)
    AS SPECIFIC_NAME,
  CASE WHEN STRIP(SYSIBM.SYSROUTINES.ORIGIN) = 'E' THEN 'EXTERNAL' ELSE 'SQL' END
    AS ROUTINE_BODY,
  SYSIBM.SYSROUTINES.TEXT
    AS ROUTINE_DEFINITION
FROM
  SYSIBM.SYSROUTINES
ORDER BY
  SYSIBM.SYSROUTINES.SCHEMA,
  SYSIBM.SYSROUTINES.NAME
WITH UR
