SELECT
  NULLIF(1, 1) AS CONSTRAINT_CATALOG,
  STRIP(SYSIBM.SYSTABCONST.CREATOR) AS CONSTRAINT_SCHEMA,
  STRIP(SYSIBM.SYSTABCONST.CONSTNAME) AS CONSTRAINT_NAME,
  NULLIF(1, 1) AS TABLE_CATALOG,
  STRIP(SYSIBM.SYSTABCONST.TBCREATOR) AS TABLE_SCHEMA,
  STRIP(SYSIBM.SYSTABCONST.TBNAME) AS TABLE_NAME,
  STRIP(SYSIBM.SYSTABCONST.TYPE) AS CONSTRAINT_TYPE,
  NULLIF(1,1) AS IS_DEFERRABLE,
  NULLIF(1,1) AS INITIALLY_DEFERRED
FROM
  SYSIBM.SYSTABCONST
ORDER BY
  SYSIBM.SYSTABCONST.TBCREATOR,
  SYSIBM.SYSTABCONST.TBNAME
WITH UR
