SELECT
  IC.*,
  '0' AS IS_AUTOINCREMENT,
  CASE WHEN C.GENERATED_ATTR ='' THEN 0 ELSE 1 END AS IS_GENERATEDCOLUMN,
  C.REMARKS,
  NULLIF(1,1) AS COMPUTED_FORMULA
FROM
  SYSIBM.SYSCOLUMNS C
  INNER JOIN SYSIBM.SYSTABLES T
    ON T.CREATOR = C.TBCREATOR AND T.NAME = C.TBNAME
  INNER JOIN SYSIBM.SYSCOLUMNS IC
    ON C.TBCREATOR = IC.TBCREATOR AND C.TBNAME = IC.TBNAME AND C.NAME = IC.NAME
ORDER BY
  TBCREATOR,
  TBNAME,
  COLNO
WITH UR
