SELECT
  NULLIF(1, 1)
    AS TRIGGER_CATALOG,
  STRIP(SYSIBM.SYSTRIGGERS.SCHEMA)
    AS TRIGGER_SCHEMA,
  STRIP(SYSIBM.SYSTRIGGERS.TRIGNAME)
    AS TRIGGER_NAME,
  CASE STRIP(SYSIBM.SYSTRIGGERS.TRIGEVENT)
    WHEN 'I' THEN 'INSERT'
    WHEN 'D' THEN 'DELETE'
    WHEN 'U' THEN 'UPDATE'
    ELSE ''
  END
    AS EVENT_MANIPULATION,
  NULLIF(1, 1)
    AS EVENT_OBJECT_CATALOG,
  SYSIBM.SYSTRIGGERS.SCHEMA
    AS EVENT_OBJECT_SCHEMA,
  SYSIBM.SYSTRIGGERS.TBNAME
    AS EVENT_OBJECT_TABLE,
  1
    AS ACTION_ORDER,
  NULLIF(1, 1)
    AS ACTION_CONDITION,
  SYSIBM.SYSTRIGGERS.TEXT
    AS ACTION_STATEMENT,
  CASE WHEN STRIP(SYSIBM.SYSTRIGGERS.GRANULARITY) = 'R' THEN 'ROW' ELSE 'STATEMENT' END
    AS ACTION_ORIENTATION,
  CASE STRIP(SYSIBM.SYSTRIGGERS.TRIGTIME)
    WHEN 'A' THEN 'AFTER'
    WHEN 'B' THEN 'BEFORE'
    WHEN 'I' THEN 'INSTEAD OF'
    ELSE ''
  END
    AS CONDITION_TIMING
FROM
  SYSIBM.SYSTRIGGERS
ORDER BY
  SYSIBM.SYSTRIGGERS.SCHEMA,
  SYSIBM.SYSTRIGGERS.TRIGNAME
WITH UR
