SELECT
  NULLIF(1, 1)
    AS VIEW_CATALOG,
	STRIP(SYSIBM.SYSVIEWDEP.DCREATOR)
	  AS VIEW_SCHEMA,
	STRIP(SYSIBM.SYSVIEWDEP.DNAME)
   	AS VIEW_NAME,
  NULLIF(1, 1)
    AS TABLE_CATALOG,
	STRIP(SYSIBM.SYSVIEWDEP.BCREATOR)
	  AS TABLE_SCHEMA,
	STRIP(SYSIBM.SYSVIEWDEP.BNAME)
	  AS TABLE_NAME
FROM
	SYSIBM.SYSVIEWDEP
WHERE
	DTYPE = 'V'
	AND BCREATOR NOT LIKE 'SYS%'
ORDER BY
	VIEW_SCHEMA,
	VIEW_NAME,
	TABLE_NAME
WITH UR
