SELECT
  NULLIF(1, 1)
    AS TABLE_CATALOG,
  STRIP(SYSIBM.SYSVIEWS.CREATOR)
    AS TABLE_SCHEMA,
  STRIP(SYSIBM.SYSVIEWS.NAME)
    AS TABLE_NAME,
  SYSIBM.SYSVIEWS.STATEMENT
    AS VIEW_DEFINITION,
  CASE WHEN STRIP(SYSIBM.SYSVIEWS.CHECK ) = 'N' THEN 'NONE' ELSE 'CASCADED' END
    AS CHECK_OPTION,
  CASE WHEN STRIP(SYSIBM.SYSVIEWS.ENABLE) = 'Y' THEN 'N/A' ELSE 'N/A' END
    AS IS_UPDATABLE
FROM
  SYSIBM.SYSVIEWS
ORDER BY
  SYSIBM.SYSVIEWS.CREATOR,
  SYSIBM.SYSVIEWS.NAME,
  SYSIBM.SYSVIEWS.ENVID
WITH UR